#require 'test/test_helper'
#require 'test/unit/fsmapper_test'
#require 'test/unit/adapters/fsadapter_test'
require 'test/unit'
load 'test/test_helper.rb'
load 'test/unit/fsmapper_test.rb'
load 'test/unit/adapters/fsadapter_test.rb'
